- model_name: ollama-gpu-dolphin-mistral-7b
  litellm_params:
    model: ollama/dolphin-mistral:7b
    api_base: http://ollama-gpu:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: ollama-gpu-qwen3-8b
  litellm_params:
    model: ollama/qwen3:8b
    api_base: http://ollama-gpu:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: ollama-gpu-gemma3-12b
  litellm_params:
    model: ollama/gemma3:12b
    api_base: http://ollama-gpu:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: ollama-gpu-qwen2.5-coder-7b
  litellm_params:
    model: ollama/qwen2.5-coder:7b
    api_base: http://ollama-gpu:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: ollama-gpu-llama3.1-8b
  litellm_params:
    model: ollama/llama3.1:8b
    api_base: http://ollama-gpu:11434
    extra_body:
      options:
        num_gpu: 99
