- model_name: local-ollama-cuda-dolphin-mistral-7b
  litellm_params:
    model: ollama/dolphin-mistral:7b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-qwen3-8b
  litellm_params:
    model: ollama/qwen3:8b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-gemma3-12b
  litellm_params:
    model: ollama/gemma3:12b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-qwen2.5-coder-7b
  litellm_params:
    model: ollama/qwen2.5-coder:7b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-llama3.1-8b
  litellm_params:
    model: ollama/llama3.1:8b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-gemma3-4b
  litellm_params:
    model: ollama/gemma3:4b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-dolphin3
  litellm_params:
    model: ollama/dolphin3:latest
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-dolphin-phi
  litellm_params:
    model: ollama/dolphin-phi:latest
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99
