- model_name: local-ollama-cuda-qwen3-8b
  litellm_params:
    model: ollama/qwen3:8b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-gemma4-e4b
  litellm_params:
    model: ollama/gemma4:e4b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-gemma4-e2b
  litellm_params:
    model: ollama/gemma4:e2b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-qwen2.5-coder-7b
  litellm_params:
    model: ollama/qwen2.5-coder:7b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-deepseek-coder-v2-16b
  litellm_params:
    model: ollama/deepseek-coder-v2:16b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-llama3.1-8b
  litellm_params:
    model: ollama/llama3.1:8b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-qwen3-abliterated-16b
  litellm_params:
    model: ollama/huihui_ai/qwen3-abliterated:16b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-gemma4-abliterated-e4b
  litellm_params:
    model: ollama/huihui_ai/gemma-4-abliterated:e4b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-deepseek-r1-8b
  litellm_params:
    model: ollama/deepseek-r1:8b
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99

- model_name: local-ollama-cuda-dolphin-phi
  litellm_params:
    model: ollama/dolphin-phi:latest
    api_base: http://ollama-cuda:11434
    extra_body:
      options:
        num_gpu: 99
