- model_name: or-nemotron-lightning
  litellm_params:
    model: openrouter/nvidia/nemotron-3.5-lightning:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-nemotron-120b
  litellm_params:
    model: openrouter/nvidia/nemotron-3-super-120b-a12b:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-nemotron-ultra
  litellm_params:
    model: openrouter/nvidia/nemotron-3-ultra-550b-a55b:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-qwen3.8-27b
  litellm_params:
    model: openrouter/qwen/qwen3.8-27b:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-dots-3-note
  litellm_params:
    model: openrouter/dots-studio/dots-3-note-preview:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-ling-3-vl
  litellm_params:
    model: openrouter/inclusionai/ling-3.0-flash-vl:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-gemma-4-31b
  litellm_params:
    model: openrouter/google/gemma-4-31b-it:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-inkling
  litellm_params:
    model: openrouter/thinkingmachines/inkling:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-nemotron-omni-30b
  litellm_params:
    model: openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-north-mini-code
  litellm_params:
    model: openrouter/cohere/north-mini-code:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-lfm-2.5-2.6b
  litellm_params:
    model: openrouter/liquid/lfm-2.5-2.6b:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-ling-3-sante
  litellm_params:
    model: openrouter/inclusionai/ling-3.0-flash-sante:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-ling-3-fin
  litellm_params:
    model: openrouter/inclusionai/ling-3.0-flash-fin:free
    api_key: os.environ/OPENROUTER_API_KEY

- model_name: or-nemotron-content-safety
  litellm_params:
    model: openrouter/nvidia/nemotron-3.5-content-safety:free
    api_key: os.environ/OPENROUTER_API_KEY
