- model_name: openai-gpt-4o
  litellm_params:
    model: openai/gpt-4o
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-gpt-4o-mini
  litellm_params:
    model: openai/gpt-4o-mini
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-o3
  litellm_params:
    model: openai/o3
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-o3-mini
  litellm_params:
    model: openai/o3-mini
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-dall-e-3
  litellm_params:
    model: openai/dall-e-3
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-gpt-image-1
  litellm_params:
    model: openai/gpt-image-1
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-whisper
  litellm_params:
    model: openai/whisper-1
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-tts-1
  litellm_params:
    model: openai/tts-1
    api_key: os.environ/OPENAI_API_KEY

- model_name: openai-tts-1-hd
  litellm_params:
    model: openai/tts-1-hd
    api_key: os.environ/OPENAI_API_KEY
