- model_name: local-speaches-cuda-whisper-distil-large-v3
  litellm_params:
    model: openai/Systran/faster-distil-whisper-large-v3
    api_base: http://speaches-cuda:8000/v1
    api_key: none
  model_info:
    mode: audio_transcription

- model_name: local-speaches-cuda-parakeet-tdt-0.6b
  litellm_params:
    model: openai/istupakov/parakeet-tdt-0.6b-v2-onnx
    api_base: http://speaches-cuda:8000/v1
    api_key: none
  model_info:
    mode: audio_transcription
